swagger: '2.0'
info:
  version: 0.0.1
  title: '大学生兼职测试api'
  description: '本api只用来给app进行测试用'
host: 'none'
produces:
- 'application/json'
paths:
  /auth:
    post:
      description: |
        登陆，返回用户基本信息和验证TOKEN
      parameters:
        - name: email
          in: formData
          description: 用户邮箱
          required: true
          type: string
        - name: password
          in: formData
          description: 密码
          required: true
          type: string
          format: password
      responses:
        '200':
          description: 登陆成功
          schema:
            $ref: '#/definitions/User'
        default:
          description: 登陆失败
          schema:
            $ref: "#/definitions/ErrorModel"
  /user:
    get:
      description: 得到某个用户的信息(如果需要登陆的话要参数要带上authtoken)
      parameters:
      - name: id
        in: query
        description: 用户的id
        required: true
        type: integer
        format: int64
      responses:
        '200':
          description: 找到用户
          schema:
            $ref: '#/definitions/UserDetail'
        default:
          description: unexpected error
          schema:
            $ref: "#/definitions/ErrorModel"
  /resumelist:
    get:
      description: 得到用户的简历列表
      parameters:
      - name: id
        in: query
        description: 用户id
        required: true
        type: integer
        format: int64
      responses:
        '200':
          description: 用户的所有简历列表
          schema:
            type: array
            items: 
              $ref: '#/definitions/Resume'
        default:
          description: unexpected error
          schema:
            $ref: "#/definitions/ErrorModel"
  /resume:
    get:
      description: 得到某份简历
      parameters:
      - name: id
        in: query
        description: 简历id
        required: true
        type: integer
        format: int64
      responses:
        '200':
          description: 简历详情
          schema:
            $ref: '#/definitions/Resume'
        default:
          description: unexpected error
          schema:
            $ref: "#/definitions/ErrorModel"
    delete:
      description: 删除简历
      parameters:
      - name: id
        in: query
        description: 简历id
        required: true
        type: integer
        format: int64
      - name: auth
        in: query
        description: 登陆获得的auth token
        required: true
        type: string
      responses:
        '200':
          description: deleted
        default:
          description: unexpected error
          schema:
            $ref: "#/definitions/ErrorModel"
    post:
      description: 添加简历
      parameters:
      - name: resume
        in: body
        description: 添加的简历
        required: true
        schema:
          $ref: '#/definitions/NewResume'
      - name: auth
        in: query
        description: 登陆获得的auth token
        required: true
        type: string
      responses:
        '200':
          description: 简历详情
          schema:
            $ref: '#/definitions/Resume'
        default:
          description: unexpected error
          schema:
            $ref: "#/definitions/ErrorModel"
  /job:
    get:
      description: 查找一个岗位的详情信息
      parameters:
      - name: id
        in: query
        description: 岗位id
        required: true
        type: integer
        format: int64
      responses:
        '200':
          description: 返回工作详情
          schema:
            $ref: '#/definitions/Job'
        default:
          description: unexpected error
          schema:
            $ref: "#/definitions/ErrorModel"
  /jobs:
    get:
      description: 查找岗位
      parameters:
      - name: keyword
        in: query
        description: 关键字
        required: false
        type: string
      - name: offset
        in: query
        description: 查找结果的偏移量（用来分页）
        required: false
        type: integer
        format: int32
      - name: max_result
        in: query
        description: 最多返回的结果
        required: false
        type: integer
        format: int32
      responses:
        '200':
          description: 返回搜索的所有岗位
          schema:
            type: array
            items:
              $ref: '#/definitions/Job'
        default:
          description: unexpected error
          schema:
            $ref: "#/definitions/ErrorModel"
definitions:
  User:
    type: 'object'
    required:
    - email
    - id
    - auth
    properties:
      id:
        type: 'integer'
        format: 'int64'
      email:
        type: 'string'
      nickname:
        type: 'string'
      avatar:
        type: 'string'
      auth:
        type: 'string'
  UserDetail:
    type: object
    required:
    - id
    properties:
      id:
        type: integer
        format: int64
      email:
        type: string
      nickname:
        type: string
      avatar:
        type: string
      sign:
        type: string
      birthday:
        type: string
        format: date
      location:
        type: string
      sex: 
        type: integer
        format: int32
      contact: 
        type: string
  Resume:
    type: object
    required:
    - id
    - user_id
    properties:
      id:
        type: integer
        format: int64
      user_id:
        type: integer
        format: int64
      name:
        type: string
      photo:
        type: string
      school:
        type: string
      introduction:
        type: string
  NewResume:
    type: object
    required:
    - user_id
    - name
    properties:
      user_id:
        type: integer
        format: int64
      name:
        type: string
      photo:
        type: string
      school:
        type: string
      introduction:
        type: string
  Job:
    type: object
    required:
    - id
    - name
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      salary:
        type: string
      description:
        type: string
      company_id:
        type: integer
        format: int64
      company_name:
        type: string
      create_time:
        type: string
        format: date
  ErrorModel:
    type: "object"
    required:
    - "code"
    - "message"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
      